# Generated by Django 5.0.1 on 2024-01-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_topic_rooms_host'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
