# Generated by Django 5.0.1 on 2024-01-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='message',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='host',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
